dist: focal
sudo: required

env:
  matrix:
    - SUITE=bionic MIRROR=http://archive.ubuntu.com/ubuntu
    - SUITE=bullseye
    - SUITE=buster
    - SUITE=focal MIRROR=http://archive.ubuntu.com/ubuntu
    - SUITE=groovy MIRROR=http://archive.ubuntu.com/ubuntu
    - SUITE=jessie
    - SUITE=sid
    - SUITE=stretch
    - SUITE=trusty MIRROR=http://archive.ubuntu.com/ubuntu
    - SUITE=xenial MIRROR=http://archive.ubuntu.com/ubuntu

matrix:
  fast_finish: true

branches:
  only:
    - master

before_install:
  - echo "deb http://archive.ubuntu.com/ubuntu/ devel main universe"
        | sudo tee /etc/apt/sources.list.d/devel.list
  - sudo apt-get update --quiet
  - sudo apt-get install --no-install-recommends --yes
        autopkgtest
        qemu-system
        qemu-utils
        vmdb2

script:
  - sudo autopkgtest-build-qemu $SUITE autopkgtest-$SUITE.img $MIRROR
